<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-TaskFlowPro.Worker-a003e2c9-9013-4a2d-8c07-a4b49fe5a097</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.6" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TaskFlowPro.Api\TaskFlowPro.Api.csproj" />
    <ProjectReference Include="..\TaskFlowPro.Shared\TaskFlowPro.Shared.csproj" />
  </ItemGroup>
</Project>
